# FROM node:latest
FROM node:16.15.1
WORKDIR '/web'
COPY ./package.json ./
RUN npm install --force
RUN npm install --legacy-peer-deps
COPY ./.env.production /
RUN npm run build

FROM nginx
COPY --from=0 /app/build /usr/share/nginx/html
COPY ../nginx/default.conf /etc/nginx/conf.d
EXPOSE 80
