steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        docker build \
        -t gcr.io/$PROJECT_ID/feedback_db \
        -f ./feedback_db/Dockerfile.prd \
        --build-arg MYSQL_PASWWORD=$$DB_PASWWORD \
        ./feedback_db

    secretEnv: ["DB_PASWWORD"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/feedback_db"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/1
      env: "DB_PASWWORD"
