steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/feedback_web",
        "-f",
        "./frontend/feedback_web/Dockerfile-prd",
        "./frontend/feedback_web",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/feedback_web"]
