steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - |
        docker build \
        -t gcr.io/$PROJECT_ID/feedback_app \
        -f ./backend/feedback_app/Dockerfile.prd \
        --build-arg ENV=prd \
        --build-arg GCP_PROJECT_ID=$$GCP_PROJECT_ID \
        --build-arg GCP_PRIVATE_KEY_ID=$$GCP_PRIVATE_KEY_ID \
        --build-arg GCP_PRIVATE_KEY=$$GCP_PRIVATE_KEY \
        --build-arg GCP_CLIENT_EMAIL=$$GCP_CLIENT_EMAIL \
        --build-arg GCP_CLIENT_ID=$$GCP_CLIENT_ID \
        --build-arg GCP_CLIENT_CERT_URL=$$GCP_CLIENT_CERT_URL \
        --build-arg GS_BUCKET_NAME=$$GS_BUCKET_NAME \
        --build-arg DB_ENGINE=django.db.backends.mysql \
        --build-arg DB_NAME=feedback \
        --build-arg DB_USER=feedback \
        --build-arg DB_PASSWORD=$$DB_PASSWORD \
        --build-arg DB_HOST=feedback_db \
        --build-arg DB_PORT=3306 \
        --build-arg DJANGO_DEBUG_MODE=False \
        ./backend/feedback_app

    secretEnv:
      [
        "GCP_PROJECT_ID",
        "GCP_PRIVATE_KEY_ID",
        "GCP_PRIVATE_KEY",
        "GCP_CLIENT_EMAIL",
        "GCP_CLIENT_ID",
        "GCP_CLIENT_CERT_URL",
        "GS_BUCKET_NAME",
        "DB_PASSWORD",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/feedback_app"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GCP_PROJECT_ID/versions/1
      env: "GCP_PROJECT_ID"
    - versionName: projects/$PROJECT_ID/secrets/GCP_PRIVATE_KEY_ID/versions/1
      env: "GCP_PRIVATE_KEY_ID"
    - versionName: projects/$PROJECT_ID/secrets/GCP_PRIVATE_KEY/versions/1
      env: "GCP_PRIVATE_KEY"
    - versionName: projects/$PROJECT_ID/secrets/GCP_CLIENT_EMAIL/versions/1
      env: "GCP_CLIENT_EMAIL"
    - versionName: projects/$PROJECT_ID/secrets/GCP_CLIENT_ID/versions/1
      env: "GCP_CLIENT_ID"
    - versionName: projects/$PROJECT_ID/secrets/GCP_CLIENT_CERT_URL/versions/1
      env: "GCP_CLIENT_CERT_URL"
    - versionName: projects/$PROJECT_ID/secrets/GS_BUCKET_NAME/versions/1
      env: "GS_BUCKET_NAME"
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/1
      env: "DB_PASSWORD"
