version: "3.1"
services:
  feedback-web:
    container_name: feedback_web
    image: node:16.15.1
    # build: ./frontend/feedback_web
    volumes:
      - ./frontend/feedback_web:/web
    working_dir: /web
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start
    
  frontend-server:
    container_name: nginx_frontend
    build: ./frontend/nginx
    ports:
      - 3001:3001
    depends_on:
      - feedback-web

  feedback-app:
    container_name: feedback_app
    # image: feedback_backend:latest
    build: ./backend/feedback_backend
    env_file: ./backend/feedback_backend/env_file.env
    volumes:
      - ./backend/feedback_backend:/app/
    working_dir: /app
    command: gunicorn --bind :8001 config.wsgi:application
    tty: true
    stdin_open: true
    # ports:
    #   - 8000:8000

  backend-server:
    container_name: nginx_backend
    build: ./backend/nginx
    ports:
      - 8000:80
    volumes:
      - ./backend/feedback_backend/config/static:/static
    working_dir: /backend
    depends_on:
      - feedback-app

  db:
    build: ./feedback_db
    container_name: feedback_db
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: feedback
      MYSQL_PASSWORD: feedback

volumes:
  db-store:
