version: "3.1"
services:
  front:
    image: fb_web:latest
    container_name: fb_web
    # volumes:
    #   - ./feedback_front:/front
    #working_dir: /front
    ports:
      - 3000:80
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    # command: npm start

  nginx:
    build: ./backend/nginx
    ports:
      - 8000:8000
    volumes:
      - ./backend/feedback_backend/config/static:/static
    working_dir: /backend
    depends_on:
      - backend
    
  backend:
    # image: feedback_backend:latest
    build: ./backend/feedback_backend
    container_name: feedback_backend
    env_file: ./backend/feedback_backend/env_file.env
    volumes:
      - ./backend/feedback_backend:/backend/
    working_dir: /backend
    expose:
      - "8001"
    # ports:
    #   - 8000:8000

  db:
    build: ./feedback_db
    container_name: feedback_db
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: feedback
      MYSQL_PASSWORD: feedback

volumes:
  db-store:
