FROM python:3.9.7
ENV PYTHONUNBUFFERED 1
RUN apt update && apt install -y sqlite3 vim less default-mysql-client
# Django ER図生成用
RUN apt install -y libgraphviz-dev graphviz pkg-config
WORKDIR /app
COPY requirements.txt ./
RUN python -m pip install --upgrade pip setuptools
RUN pip install -r requirements.txt
COPY . ./
ENTRYPOINT [ "bash", "entry_point.sh" ]
CMD [ "uwsgi", "--socket", ":8001", "--chdir", "/app", "--module", "config.wsgi"]
EXPOSE 8000